### ISSUE TITLE
make new function to get config.json and put try and except around it. So in the beginning if config file is not found the server should not startup. 

### ISSUE THREAD

**Issue by NiharZanwar** [garrysawyers3007/Object-Detection#1]
https://github.com/garrysawyers3007/Object-Detection/blob/077cae8b5fc4bcee533480966db4cd339089c0cc/Functions.py#L10

**Comment by garrysawyers3007** [comment]
Surrounding it in try and except doesn't look necessary besides without that it already gives FileNotFoundError.
